# The Process for Creating a Separate Conda-Smithy Feedstock

Starting from link:https://github.com/phreed/my-conda-pkg-feedstock[the sample].
There are other tutorials out there but `conda-smithy` is moving quickly.

Note that this feedstock repository was constructed from the `./recipes/oracle-jdk` recipe directory.
It was populated with an assortment of files including the file `recipe/meta.yaml`.
[source,yaml]
----
include::meta.yaml[]
----

This is all that is needed to create this git repository `oracle-jdk-feedstock`.
I do not want to contaminate the original repository so the init is performed
from the directory containing the original `conda-forge` source.
[source,cmd]
----
mamba smithy init .\staged-recipes\recipes\oracle-jdk
----

The feedstock needs to be registered with github.
First the tokens need to be made available to `mamba smithy`.
The tokens are placed in the `~/.conda-smithy` folder and are given names corresponding to the tool.

anaconda.token::: https://anaconda.org/mesomorph/settings/access
github.token:::  https://github.com/settings/tokens

[source,cmd]
----
mamba smithy register-github --user phreed ./my-conda-pkg-feedstock
----

The tricky part of this is the registration of all the tokens required by the various build tooling.
The tokens are placed in files in the `~/.conda-smithy` folder and are given names corresponding to the tool.
**Each of these files contains the token and only the token**.

These tools frequently change their usage policies and where to acquire their respective tokens.
Having many builders is important for `conda-forge` as it needs to be concerned with issues like performance.
But, for building channels that parallel `conda-forge` supporting most of these tools is a headache.
If you need one of these tools
link:https://github.com/conda-forge/conda-smithy/tree/main/conda_smithy/templates[the template]
for each of these build tools may be informative.
It is helpful to disable the tools which you do not need.
See `mamba smithy register-ci -h` for a list of all the flags.

I only use the tokens for `github` which does my builds, and `anaconda` which is my target.

[source,cmd]
----
mamba smithy register-ci --user phreed --without-drone --without-azure --without-appveyor --feedstock_directory ./my-conda-pkg-feedstock
----

Now build the scripts needed by the specified tooling.

[source,cmd]
----
mamba smithy rerender --feedstock_directory  .\my-conda-pkg-feedstock
----
Finally, push the configured feedstock to github for building and deployment.

[source,cmd]
----
cd my-conda-pkg-feedstock
git commit -m "MNT: Re-rendered with conda-build 3.21.8, conda-smithy 3.19.0, and conda-forge-pinning 2022.04.28.22.31.46"
git push upstream main
----

That seems to do the trick.
