# This feedstock wraps existing binary distributions.
{% set name = "oracle-jdk-dummy" %}
{% set version = "8.0" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

build:
  number: 0

requirements:
  build:
    - numpy {{ numpy }}
  host: []
  run: []

test:
  requires:
  files:
  commands:
    - test -d ${PREFIX}/bin  # [linux]
    - test -d ${PREFIX}/conda-meso/oracle-jdk-dummy-8.0_0  # [linux]
    - if exist %PREFIX%\bin  # [win]
    - if exist %PREFIX%\conda-meso\oracle-jdk-dummy-8.0_0  # [win]

about:
  home: https://github.com/phreed/oracle-jdk-dummy-feedstock
  license: MIT
  license_file: LICENSE.txt
  summary: 'Meta-package for Oracle JDK'
  description: |
    This module provides a dummy installer for the Oracle JDK.
    It does not install the Oracle JDK package.
    It adds the Oracle JDK into the specified Conda environment.
    It expects the appropriate Oracle JDK to have been previously acquired.
    It may be acquired and installed from 
    https://www.oracle.com/java/technologies/downloads/#java8-windows
    https://www.oracle.com/java/technologies/downloads/#java8-linux
  dev_url: https://github.com/phreed/oracle-jdk-dummy-feedstock
  doc_url: https://github.com/phreed/oracle-jdk-dummy-feedstock

extra:
  recipe-maintainers:
    - 'phreed'
