{% set name = "oracle-jdk" %}
{% set version = "8.0" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  path: './src'

build:
  number: 0

requirements:
  build:
    - numpy {{ numpy }}
  host: []
  run: []

test:
  commands:
    - test ! -d ${PREFIX}/foo  # [linux]
    - if not exist %PREFIX%\foo  # [win]

#outputs:
#  - name: '{{ name }}'
#    - sel(linux): []
#    - sel(win): []

about:
  home: https://github.com/babeloff/oracle_jdk_boa
  license: MIT
  license_file: LICENSE.txt
  summary: 'Meta-package for Oracle JDK'
  description: |
    This module provides a meta installer for the Oracle JDK.
    It expects the appropriate Oracle JDK to have been previously acquired.
    It may be acquired from 
    https://www.oracle.com/java/technologies/downloads/#java8-windows
    https://www.oracle.com/java/technologies/downloads/#java8-linux
  dev_url: https://github.com/babeloff/oracle_jdk_boa
  doc_url: https://github.com/babeloff/oracle_jdk_boa

extra:
  recipe-maintainers:
    - 'phreed'
