github:
  user_or_org: phreed
channels:
  targets:
    - [mesomorph,main]
provider:
  osx: github_actions
  linux: github_actions
  win: github_actions
github_actions:
  upload_packages: True
upload_on_branch: main

